// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cisgldwuyslmucrfeibi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpc2dsZHd1eXNsbXVjcmZlaWJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMTM2NzAsImV4cCI6MjA1NzY4OTY3MH0.XA02g97f8Gf3fQDStIakvuDpPtnaj7MKZfrrSxRr4kM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);